### ISSUE TITLE
Update for 1.12.2?

### ISSUE THREAD

**Issue by NanoAi** [bergerhealer/NoLagg#3]

**Comment by johncsuti** [comment]
Can you not read the readme.md?? No updates ever!!

**Comment by NanoAi** [comment]
Just because it's deprecated here doesn't mean that no one has ever made a fork or knows an alternative. Plus what's the point on even responding on a post that's from 2018, in 2020?

**Comment by johncsuti** [comment]
You want an alternative use  paper most of this repository has been made into paper done. You also never said you wanted an alternative or a fork. You just want a update on a old useless plugin.

**Comment by bbayu123** [comment]
Closing issue, will not update
